---
name: Java CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [8, 11, 15]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/99-problems/99-problems/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_test_uses-checkout_18
      - run: rm starting_test_uses-checkout_18
      - uses: actions/checkout@v1
      - run: touch starting_test_SetupJDK_19
      - run: rm starting_test_SetupJDK_19
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: touch starting_test_TestwithMaven_23
      - run: rm starting_test_TestwithMaven_23
      - name: Test with Maven
        run: mvn test -B --file java8/pom.xml
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          echo pwd
          ls -la
          python .github/workflows/script.py
      - name: Check push directory exit code
        run: |
          echo 'push failed, trying pull and then push'
          git config --global user.name 'UT-SE-Research'
          git config --global user.email 'ocibsummerresearch2022@gmail.com'
          git add .
          git commit -m 'rebased and pushed ${{ github.head_ref }}'
          while ! git push origin 1676957487-c0ae930; do
            git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676957487-c0ae930
            git remote set-url origin https://UT-SE-Research:${{ secrets.API_TOKEN_GITHUB }}@github.com/UT-SE-Research/ci-analyzes.git
            git push origin 1676957487-c0ae930
          done
...
